# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c57e27d7446bbe7d27607ea73bcf287bc160277e702aa35f1f33a1499d4ab65b219b2bbecfd05c456be70c33c5b91f89e6ee1c054c4b4e6aa6fc96809767f010

test:
  secret_key_base: 24fb09cc4a255797d5d196600c27999eaecdaaa092df49aca19f621d9f51d885e56d5bbb5d3ddd678b0a6b5e6079836bc9f13a093259f3c042eb760c12a5281d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
